# _config.yml

# Site settings
title: "Your Site Title" # The title of your site
description: "A brief description of your site" # A short description for your site

# Build settings
safe: false # Disables safe mode, allowing custom plugins
auto: true # Automatically regenerate the site when files are modified
server: false # Disables the built-in server
server_port: 4000 # Port number for the built-in server
baseurl: "" # Base URL for your site (leave empty if hosted at the root)
url: "https://pschaus.github.io" # The URL of your site
source: "." # The source directory for your site's content
destination: "./_site" # The directory where the generated site will be placed
plugins_dir: "./_plugins" # Directory for custom plugins

# Markdown settings
markdown: kramdown # Markdown processor

# Permalink settings
permalink: date # Permalink style (e.g., /:categories/:year/:month/:day/:title.html)

# Other settings
future: true # Publish posts with future dates

